export const USER_SETUP="USER_SETUP";
export const USER_LOG_OUT="USER_LOG_OUT";
export const CONVO_SETUP="CONVO_SETUP";
export const USER_IMAGE_SETUP="USER_IMAGE_SETUP";
export const USER_PUSH_TOKEN_SETUP="USER_PUSH_TOKEN_SETUP";

export const SETUP_FONT_SIZE="SETUP_FONT_SIZE";